### ISSUE TITLE
Fast track object missed

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#106]
ZTF got it before ATLAS, but curious to know why this was not associated with NGC 3478

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1105927631460726900/

**Comment by thespacedoctor** [comment]
The 'synonymous' matching at the core of an SDSS galaxy was the issue. 'Synonym' matching is done first in the list of crossmatches and if one or more is found then sherlock stops, otherwise it precedes to 'association' matches. 

The reasoning here is that if we match right on top of a stellar source then why waste time and cpu trying to match other sources from further afield. Same should be true of the cores of galaxies, but some catalogue sources tagged as galaxies are ... not galaxies.

Note this is a separate (but related) issue to past issue of SDSS photoz galaxies incorrectly matching due to photoz --> physical distance being unreliable.

I've reworked some of the algorithm to remove this issue (from Glade, 2MASS and SDSS in particular).

https://gist.github.com/thespacedoctor/5ed7e1f4018dc2c501b0d9b9d8f6cbff#file-sherlock_script_settings-yaml

**Comment by genghisken** [comment]
Has the ATLAS algorithm been updated?  If not, I'll do it now, along with the Pan-STARRS ones.

**Comment by thespacedoctor** [comment]
nope - if you want to give me a list of exact locations for the yaml file I can update it each time.
