### ISSUE TITLE
Add Pan-STARRS and Gaia DR2 catalogues. 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#66]
This is a big one, but would be a major upgrade and enhancement. 

Adding the Pan-STARRS2 and Gaia DR2 catalogues is the next major enhancement. I think we need to tackle it now, well in advance of LIGO O3, and the new Pan-STARRS survey 

We'll need both catalogues locally, with Pan-STARRS mean mags and the parameters required for Nigel's star-galaxy separator.

**Comment by thespacedoctor** [comment]
Add required indexes to the Gaia DR2 table for the magnitude columns.

**Comment by thespacedoctor** [comment]
indexing complete and DR2 integrated into the search algorithm

**Comment by thespacedoctor** [comment]
FYI here are the statements to create the required database views for Gaia DR2:

```sql
CREATE VIEW `tcs_view_unclear_gaia_dr2` AS
    SELECT 
        *
    FROM
        `tcs_view_star_gaia_dr2`
    WHERE
        (`tcs_view_star_gaia_dr2`.`phot_g_mean_mag` > 20);


CREATE VIEW `tcs_view_star_gaia_dr2` AS
    SELECT 
        *
    FROM
        `tcs_view_star_gaia_dr2`
    WHERE
        (`tcs_view_star_gaia_dr2`.`phot_g_mean_mag`  <= 20);
```

**Comment by genghisken** [comment]
I guess this is a cut/paste error, but in the FROM and WHERE clauses you presumably mean `tcs_cat_gaia_dr2` in BOTH cases.  I've just had a look on DB4, and the `tcs_view_unclear_gaia_dr2` view is incorrect, since it references the tcs_view_star_gaia_dr2 view and NOT the tcs_cat_gaia_dr2 table!

According to your setup, tcs_view_unclear_gaia_dr2 will return zero rows.  In fact...

```
mysql> select count(*) from tcs_view_unclear_gaia_dr2;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

**Comment by thespacedoctor** [comment]
Ahh - yes of course I mean `tcs_cat_gaia_dr2`!
