### ISSUE TITLE
Distance modulus being wrongly labeled as 0

### ISSUE THREAD

**Issue by dsoneill** [thespacedoctor/sherlock#71]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1001401730231135600/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1165235481282717100/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1200433920390707800/

**Comment by thespacedoctor** [comment]
The issue here seems to be that if a *direct* distance has been measured for the galaxy, as opposed to a distance implied from a redshift, the empty *implied* distance modulus is still read from the database.

I've fixed this now. Clicking on the linked ATLAS examples provided shows that *m-M* is now populated.

I also cleared an reclassified all non-garbage source affected by this issue (~270 transients).

```sql
UPDATE atlas_diff_objects 
SET 
    sherlockClassification = NULL
WHERE
    id IN (SELECT 
            *
        FROM
            (SELECT DISTINCT
                (id)
            FROM
                atlas_diff_objects a, sherlock_classifications c
            WHERE
                a.id = c.transient_object_id
                    AND a.detection_list_id IN (1 , 2, 3, 4, 5)
                    AND c.annotation LIKE '%</em> None%') AS a);
```
