### ISSUE TITLE
Object should have been associated with nearby galaxy

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#81]
This object should have been in the Fast Track List.  But it was associated with a DR12 SDSS photometric redshift object.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1144547401502348500/

**Comment by smarttgit** [comment]
Also - similar problem. There is redshift in NED but not picked up, Sherlock locks on the photoz value instead. 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1124138700090957300/

**Comment by smarttgit** [comment]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1140338850335836600/
Should have been associated with NGC5419

**Comment by smarttgit** [comment]
Important to get the ranking right when we add Gaia DR2 and Pan-STARRS - let's carefully check

**Comment by smarttgit** [comment]
Error here in calculating offset
https://psweb.mp.qub.ac.uk/sne/ps2o3/psdb/candidate/1005516380255945800/

**Comment by thespacedoctor** [comment]
> Error here in calculating offset
> https://psweb.mp.qub.ac.uk/sne/ps2o3/psdb/candidate/1005516380255945800/
> 14377.7 Kpc!!

This seems like an old bug - Ken where is sherlock getting called for ps2 and what machine is the DB hosted on?

**Comment by genghisken** [comment]
Interesting...  All the ps1 and ps2 databases on db0 call the same instance of Sherlock.  I think I upgraded it relatively recently as a result of a similar ludicrous offset.  It's version 1.6.5 according to the dist_info directory.  I think we last upgraded it on October 21st 2019.  I can force through another upgrade if it's out of date, though bear in mind that this is still python 2.7 environment.

**Comment by thespacedoctor** [comment]
Consolidating problem objects ...

![Candidate 1144547401502348500](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1144547401502348500/) - latching onto photoz galaxy
![Candidate 1124138700090957300](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1124138700090957300/) - latching onto photoz galaxy
![Candidate 1153855491043441100](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1153855491043441100/) - latching onto photoz galaxy
![Candidate 1140338850335836600](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1140338850335836600/) - Should have been associated with NGC5419
![Candidate 1005516380255945800] (https://psweb.mp.qub.ac.uk/sne/ps2o3/psdb/candidate/1005516380255945800/) -- wrong offset

**Comment by thespacedoctor** [comment]
Issues 1-4 are due to the annoying bug causing the transient match to latch onto the photoz 'galaxy' coincident with the transient. Generally these are measurements of knots in larger galaxy and not true galaxies themselves.

I have now *severely* downgraded galaxies with photoz measurements in the ranking algorithm and all 1-4 transients above now get matched correctly with the large galaxies. 

Transient 5 is a separate issue entirely - this is a separate issue that I can't reproduce. I am getting the correct association with the little galaxy coincident with the transient. Possibly something crashed on db0 whenever Sherlock was being run for this source?
